apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.production.yml
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - image: nginx:latest
        name: gateway
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /TeachShare-WebApp
          name: gateway-claim0
        - mountPath: /etc/nginx/conf.d
          name: gateway-claim1
        - mountPath: /code/static
          name: teachshare-django-static
        - mountPath: /code/media
          name: teachshare-django-media
      restartPolicy: Always
      volumes:
      - name: gateway-claim0
        persistentVolumeClaim:
          claimName: gateway-claim0
      - name: gateway-claim1
        persistentVolumeClaim:
          claimName: gateway-claim1
      - name: teachshare-django-static
        persistentVolumeClaim:
          claimName: teachshare-django-static
      - name: teachshare-django-media
        persistentVolumeClaim:
          claimName: teachshare-django-media
status: {}
