apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.production.yml
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: gcr.io/teach-share-200700/teachshare_web:1.0.0
        name: web
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: web-claim0
        - mountPath: /code/static
          name: teachshare-django-static
        - mountPath: /code/media
          name: teachshare-django-media
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: teachshare-django-static
        persistentVolumeClaim:
          claimName: teachshare-django-static
      - name: teachshare-django-media
        persistentVolumeClaim:
          claimName: teachshare-django-media
status: {}
