version: '2.2'

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: teachshare
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
  # web:
  #   build: ./TeachShare_WebApp/.
  #   command: bash -c "./TeachShare_WebApp/wait-for-it.sh -h db -p 5432 -- python3 TeachShare_WebApp/manage.py migrate && python3 TeachShare_WebApp/manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - search
  vue:
    build: Frontend/.
    command: npm run dev 
    volumes:
      - ./Frontend/teach-share/.:/code/.
    ports:
      - "8080:8080"
    depends_on:
      - db

  search:
    image: elasticsearch:2.4
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
volumes:
  esdata1:
    driver: local