version: '2.2'

services:
  db:
    image: postgres
    networks:
      - teachnet
    ports: 
      - 5432:5432
    networks:
      - teachnet
    restart: always
    environment:
      POSTGRES_DB: teachshare
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
  web:
    build: 
      context: ./TeachShare_WebApp
      dockerfile: Production.yml
    networks:
      - teachnet
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn --bind 0.0.0.0:8000 TeachShare_WebApp.wsgi:application"
    volumes:
      - .:/code
      - django-static:/code/static
      - django-media:/code/media
    networks:
      - teachnet
    ports:
      - 8000:8000
    depends_on:
      - db
      - search
  celery:
    build: 
      context: ./TeachShare_WebApp
      dockerfile: Production.yml
    command: bash -c "celery -A TeachShare_WebApp worker -l info -B"
    networks:
      - teachnet
    volumes:
      - .:/code
      - django-static:/code/static
      - django-media:/code/media
    depends_on:
      - web
  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./TeachShare_WebApp:/TeachShare_WebApp
      - ./TeachShare_WebApp/nginx:/etc/nginx/conf.d
      - django-static:/code/static
      - django-media:/code/media
    depends_on:
      - web
    networks:
      - teachnet
  # vue:
  #   build: Frontend/.
  #   networks:
  #     - teachnet
  #   command: npm run dev 
  #   volumes:
  #     - ./Frontend/teach-share/.:/code/.
  #   networks:
  #     - teachnet
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    hostname: search
    environment:
      - ELASTIC_PASSWORD=
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - teachnet
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - teachnet
volumes:
  django-static:
    driver: local
  django-media:
    driver: local
  esdata2:
    driver: local
networks:
  teachnet: