
POST http://localhost:8000/auth/token HTTP/1.1
content-type: application/json

{
    "client_id": "232250430081-c7aicgo6hrj04074sdhruurc8dm9un2b.apps.googleusercontent.com",
    "client_secret": "UcvpIOjRuIOJ_6NT9CYUHraA",
    "grant_type": "password",
    "username": "bryan.mccoid",
    "password": ""
}
