# Generated by Django 2.0.1 on 2018-01-23 21:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180123_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
