# Generated by Django 2.0.3 on 2018-05-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180524_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_post', 'Can View Post'),)},
        ),
    ]
