# Generated by Django 2.0.3 on 2018-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_attachment_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'Game'), (1, 'Lab'), (2, 'Lecture')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Preschool'), (1, 'Kindergarten'), (2, 'First Grade'), (3, 'Second Grade'), (4, 'Third Grade'), (5, 'Fourth Grade'), (6, 'Fifth Grade'), (7, 'Sixth Grade'), (8, 'Seventh Grade'), (9, 'Eighth Grade'), (10, 'Ninth Grade'), (11, 'Tenth Grade'), (12, 'Eleventh Grade'), (13, 'Twelfth Grade')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.IntegerField(choices=[(0, 'Math'), (1, 'English Language Arts'), (2, 'Physical Sciences'), (3, 'Life Sciences'), (4, 'Earth and Space Sciences'), (5, 'Engineering, Technology, and the Applications of Science')], default=0),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
