# Generated by Django 2.0.3 on 2018-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180419_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
