# Generated by Django 2.0.3 on 2018-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_standard_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='subject',
            field=models.IntegerField(choices=[(0, 'Math'), (1, 'English Language Arts'), (2, 'Physical Sciences'), (3, 'Life Sciences'), (4, 'Earth and Space Sciences'), (5, 'Engineering, Technology, and the Applications of Science')], default=0),
        ),
    ]
