# Generated by Django 2.0.3 on 2018-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_standard_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='standards',
            field=models.ManyToManyField(blank=True, to='posts.Standard'),
        ),
    ]
