# Generated by Django 2.0.3 on 2018-05-21 02:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180424_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, default='#96e6b3', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='layout',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'h': 30, 'i': '0', 'w': 2, 'x': 0, 'y': 0}),
        ),
    ]
