# Generated by Django 2.0.3 on 2018-05-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180520_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='layout',
        ),
    ]
