# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTaught',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='accounts.UserProfile')),
            ],
        ),
    ]
