# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subjecttaught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subjectTaught',
        ),
        migrations.AlterField(
            model_name='subjecttaught',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.UserProfile'),
        ),
    ]
