# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170722_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
