# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170717_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTaught',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='checkboxStr',
        ),
        migrations.AddField(
            model_name='gradetaught',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
