# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170722_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Files',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
