# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 02:17
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170722_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fileLocation',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
