# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170714_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ident',
        ),
    ]
