# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_post_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
