# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:30
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=18)),
                ('file_name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to=accounts.models.upload_to)),
            ],
        ),
    ]
