# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0007_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id', models.IntegerField(default=0)),
            ],
        ),
    ]
