# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Files',
        ),
    ]
