# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_attachment'),
        ('accounts', '0008_auto_20170720_1712'),
    ]

    operations = [
    ]
