# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170720_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Files',
        ),
    ]
