# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_attachment'),
        ('accounts', '0009_remove_post_files'),
    ]

    operations = [
    ]
