# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20170721_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
