# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170721_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='post',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
