# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170721_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Files',
        ),
    ]
