# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_post_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
