# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_post_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Files',
            new_name='file',
        ),
    ]
