# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170721_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='Files',
        ),
    ]
