apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 6379
  selector:
    app: cache
  type: "NodePort"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cache
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: Always
        name: cache
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 6379
          name: mysql
        volumeMounts:
        - name: redis-storage
          mountPath: /var/lib/redis
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # this is where the volume/claim config goes so that redis can dump it's db to persistent
      # memory every so often.
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
status: {}
