apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
  - port: 9200
    name: http
    protocol: TCP
  - port: 9300
    name: transport
    protocol: TCP
  selector:
    app: search
  type: "NodePort"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-pv-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: search
  name: search
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: search
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers: 
      - env:
        - name: ELASTIC_PASSWORD
          value: ""
        - name: discovery.type
          value: "single-node"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.2
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        name: search
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: search-storage
          mountPath: /data
          # mountPath: /usr/share/elasticsearch/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      # this is where the volume/claim config goes so that redis can dump it's db to persistent
      # memory every so often.
      volumes:
      - name: search-storage
        persistentVolumeClaim:
          claimName: search-pv-claim
status: {}
